name: shelf_enhanced
description: A complete framework for building web applications using the shelf package.
repository: https://gitbhub.com/tiagualvs/shelf_enhanced.git
version: 1.0.8

environment:
  sdk: ^3.0.0

dependencies:
  mime: ^2.0.0
  shelf: ^1.4.2
  shelf_multipart: ^2.0.1
  shelf_proxy: ^1.0.4
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
